### ISSUE TITLE
Constraint on fixed-sizes arrays?

### ISSUE THREAD

**Issue by edcote** [mciepluc/cocotb-coverage#51]
Not an issue as much as a feature request and/or guidance to potentially help with such request.

What would be needed to support such a structure:

```python
self.my_very_own_array = [0] * 16
for i in range(16)
  self.add_rand(f'my_very_own_array[{i}]', [0, 1])
```

**Comment by mciepluc** [comment]
@edcote 
I am sorry I have missed you created an issue.
A general comment is that if all you want to do is a simple randomization in an array, you should not bother the constraint solver with this. That's why ```post_randomize()``` function is in there. Check [here](https://cocotb-coverage.readthedocs.io/en/latest/tutorials.html#randomization-order-and-performance-issues). If you face specific problem with this feature, please let me know.
